version: '3.9'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
       - ./:/MusicRecBack
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WATCHPACK_POLLING=true
    ports:
      - "8000:80"

  db:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: 